# Generated by Django 4.2.5 on 2023-09-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
                'indexes': [models.Index(fields=['-created'], name='main_social_created_650801_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=1000)),
                ('icon', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'indexes': [models.Index(fields=['-created'], name='main_contac_created_c2a896_idx')],
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/about')),
                ('name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('years_of_work', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('resume_file', models.FileField(upload_to='media/about')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_about', to='main.contact')),
                ('socials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_about', to='main.social')),
            ],
        ),
    ]
