# Generated by Django 4.2.5 on 2023-09-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='about',
            name='socials',
        ),
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='main.about'),
            preserve_default=False,
        ),
    ]
