# Generated by Django 4.2.5 on 2023-09-26 16:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_about_contacts_remove_about_socials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=main.models.PathAndRename('/about')),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume_file',
            field=models.FileField(upload_to=main.models.PathAndRename('/about')),
        ),
    ]
